#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/init.zsh"
fi

autoload -Uz promptinit
promptinit
prompt liekos
# Customize to your needs...
export EDITOR="nvim"
export VISUAL="nvim"

[ -f ~/.config/nvim/plugged/gruvbox/gruvbox_256palette.sh ] && \
	source ~/.config/nvim/plugged/gruvbox/gruvbox_256palette.sh

# Python Virtualenvs

[ -f /usr/bin/virtualenvwrapper.sh ] && source /usr/bin/virtualenvwrapper.sh && export WORKON_HOME="~/.virtualenvs/"


# Aliases
alias vim="nvim"
alias e="vim"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
