#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/init.zsh"
fi

autoload -Uz promptinit
# set prompt
promptinit && prompt liekos
# Customize to your needs...
export EDITOR="nvim"
export VISUAL="nvim"


if [ -f ~/.config/nvim/plugged/gruvbox/gruvbox_256palette.sh ]; then
	source ~/.config/nvim/plugged/gruvbox/gruvbox_256palette.sh
fi

# Python Virtualenvs
if [ -f /usr/bin/virtualenvwrapper.sh ]; then
    source /usr/bin/virtualenvwrapper.sh
    export WORKON_HOME="~/.virtualenvs/"
fi

# Aliases
alias vim="nvim"
alias vi="vim"
alias e="vim"
alias cat="bat"
alias find="fd"
alias ag="ag --color-match '01;31' --color-path '01;34' --color-line-number '01;30' --nogroup"

if command -v htop >/dev/null 2>&1; then
    alias htop="htop --tree"
fi

[ ! -f "$HOME/.ignore" ] && touch ~/.ignore

export FZF_DEFAULT_COMMAND="fd --type f --hidden --ignore-file ~/.ignore"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--preview "bat --color always {}"'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
