#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload -Uz promptinit
promptinit
prompt liekos
# Customize to your needs...
export EDITOR="nvim"
export VISUAL="nvim"

source ~/.config/nvim/plugged/gruvbox/gruvbox_256palette.sh

# Python Virtualenvs
export WORKON_HOME="~/.virtualenvs/"
source /usr/bin/virtualenvwrapper.sh


# Aliases
alias vim="nvim"
alias e="vim"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
